services:
  - type: web
    name: business-scraper
    runtime: docker
    buildCommand: ""
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 180 --workers 1 --threads 1 --worker-class sync app:app